#!/usr/bin/env Rscript

# Chapter 06 exploration sandbox
# Focus: implementation patterns for descriptive statistics in R

options(repos = c(CRAN = "https://cloud.r-project.org"))

install_if_missing <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
  }
}

needed <- c("tidyverse", "janitor", "gtsummary", "gt")
invisible(lapply(needed, install_if_missing))

library(tidyverse)
library(janitor)
library(gtsummary)
library(gt)

out_dir <- "_explore/notes"
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

# ------------------------------------------------------------------
# Data prep
# ------------------------------------------------------------------
diabetes_raw <- read_csv("data/diabetes.csv", show_col_types = FALSE)

diabetes <- diabetes_raw |>
  clean_names() |>
  mutate(
    diabetes_5y = forcats::fct_relevel(diabetes_5y, "neg", "pos"),
    bmi_class = case_when(
      bmi < 18.5 ~ "Underweight",
      bmi < 25 ~ "Normal",
      bmi < 30 ~ "Overweight",
      TRUE ~ "Obesity"
    ) |> factor(levels = c("Underweight", "Normal", "Overweight", "Obesity"))
  )

# ------------------------------------------------------------------
# 1) Continuous summaries (overall)
# ------------------------------------------------------------------
continuous_summary <- diabetes |>
  summarise(
    across(
      .cols = c(age, bmi, glucose_mg_dl, dbp_mm_hg),
      .fns = list(
        n = ~sum(!is.na(.x)),
        mean = ~mean(.x, na.rm = TRUE),
        sd = ~sd(.x, na.rm = TRUE),
        median = ~median(.x, na.rm = TRUE),
        iqr = ~IQR(.x, na.rm = TRUE),
        min = ~min(.x, na.rm = TRUE),
        max = ~max(.x, na.rm = TRUE)
      ),
      .names = "{.col}_{.fn}"
    )
  )

# ------------------------------------------------------------------
# 2) Grouped summaries by outcome
# ------------------------------------------------------------------
by_outcome_summary <- diabetes |>
  group_by(diabetes_5y) |>
  summarise(
    n = n(),
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE),
    mean_glucose = mean(glucose_mg_dl, na.rm = TRUE),
    median_glucose = median(glucose_mg_dl, na.rm = TRUE),
    .groups = "drop"
  )

# ------------------------------------------------------------------
# 3) Categorical counts + proportions
# ------------------------------------------------------------------
bmi_by_outcome <- diabetes |>
  count(diabetes_5y, bmi_class) |>
  group_by(diabetes_5y) |>
  mutate(prop_pct = 100 * n / sum(n)) |>
  ungroup()

# ------------------------------------------------------------------
# 4) Missingness summary
# ------------------------------------------------------------------
missingness <- tibble(variable = names(diabetes)) |>
  mutate(
    n_missing = map_int(variable, ~sum(is.na(diabetes[[.x]]))),
    pct_missing = 100 * n_missing / nrow(diabetes)
  ) |>
  arrange(desc(pct_missing))

# ------------------------------------------------------------------
# 5) Publication-ready baseline table via gtsummary
# ------------------------------------------------------------------
tbl1 <- diabetes |>
  select(diabetes_5y, age, bmi, glucose_mg_dl, dbp_mm_hg, bmi_class) |>
  tbl_summary(
    by = diabetes_5y,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p}%)"
    ),
    digits = all_continuous() ~ 1,
    missing = "ifany",
    label = list(
      age ~ "Age (years)",
      bmi ~ "Body mass index (kg/m^2)",
      glucose_mg_dl ~ "Glucose (mg/dL)",
      dbp_mm_hg ~ "Diastolic blood pressure (mmHg)",
      bmi_class ~ "BMI class"
    )
  ) |>
  add_overall(last = TRUE) |>
  bold_labels()

# Save gtsummary table as HTML
html_path <- file.path(out_dir, "ch06-gtsummary-table.html")
as_gt(tbl1) |>
  gtsave(filename = html_path)

# ------------------------------------------------------------------
# Notes
# ------------------------------------------------------------------
note_lines <- c(
  "# Chapter 06 Exploration Notes",
  "",
  "Generated by: _explore/scripts/ch06_descriptive_stats_explore.R",
  "",
  "## Quick dataset profile",
  sprintf("- Rows: %s", nrow(diabetes)),
  sprintf("- Columns: %s", ncol(diabetes)),
  "",
  "## Grouped summary by diabetes outcome",
  paste(capture.output(print(by_outcome_summary)), collapse = "\n"),
  "",
  "## Missingness (top 5 variables)",
  paste(capture.output(print(head(missingness, 5))), collapse = "\n"),
  "",
  "## Categorical example: BMI class by outcome",
  paste(capture.output(print(bmi_by_outcome)), collapse = "\n"),
  "",
  "## Publication-ready table",
  sprintf("- Saved HTML: %s", html_path),
  "",
  "## Writing notes",
  "- Keep chapter implementation-focused: use summarise(across()), count(), and group_by() patterns.",
  "- Keep statistics terminology precise but concise.",
  "- Position gtsummary near the end as publication-ready workflow."
)

writeLines(note_lines, file.path(out_dir, "ch06-exploration-notes.md"))

# Also save raw objects for quick inspection if needed
saveRDS(
  list(
    continuous_summary = continuous_summary,
    by_outcome_summary = by_outcome_summary,
    bmi_by_outcome = bmi_by_outcome,
    missingness = missingness
  ),
  file = file.path(out_dir, "ch06-exploration-objects.rds")
)

message("Exploration complete.")
message("- Notes: _explore/notes/ch06-exploration-notes.md")
message("- GTSummary HTML: _explore/notes/ch06-gtsummary-table.html")
